# Generated by Django 5.0.7 on 2024-09-02 00:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customerregistration_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerRegistration',
            new_name='Customer',
        ),
    ]
